name: Build code

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'

      - name: Build
        run: ./mvnw compile

      - name: Tests
        run: ./mvnw verify

