name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test-ci

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install PNPM
        uses: pnpm/action-setup@v6
        with:
          package_json_file: slides/package.json

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: slides/.nvmrc
          cache: pnpm
          cache-dependency-path: slides/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./slides
        run: pnpm install

      - name: Build
        working-directory: ./slides
        run: pnpm build --base /hands-on-workshop-kotlin/

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v5
        with:
          path: slides/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
